CREATE PROCEDURE [dbo].[usp_UpdateEndUserRole]
    @CallingEndUserId UNIQUEIDENTIFIER,
    @Id UNIQUEIDENTIFIER,
    @Name NVARCHAR(850) = NULL,
    @HasCreatingAssetPermission BIT = NULL,
    @HasReadingAssetPermission BIT = NULL,
    @HasUpdatingAssetPermission BIT = NULL,
    @HasDeletingAssetPermission BIT = NULL,
    @HasCreatingBuildingPermission BIT = NULL,
    @HasReadingBuildingPermission BIT = NULL,
    @HasUpdatingBuildingPermission BIT = NULL,
    @HasDeletingBuildingPermission BIT = NULL,
    @HasCreatingCategoryPermission BIT = NULL,
    @HasReadingCategoryPermission BIT = NULL,
    @HasUpdatingCategoryPermission BIT = NULL,
    @HasDeletingCategoryPermission BIT = NULL,
    @HasCreatingCompanyPermission BIT = NULL,
    @HasReadingCompanyPermission BIT = NULL,
    @HasUpdatingCompanyPermission BIT = NULL,
    @HasDeletingCompanyPermission BIT = NULL,
    @HasCreatingDepartmentPermission BIT = NULL,
    @HasReadingDepartmentPermission BIT = NULL,
    @HasUpdatingDepartmentPermission BIT = NULL,
    @HasDeletingDepartmentPermission BIT = NULL,
    @HasCreatingEmployeePermission BIT = NULL,
    @HasReadingEmployeePermission BIT = NULL,
    @HasUpdatingEmployeePermission BIT = NULL,
    @HasDeletingEmployeePermission BIT = NULL,
    @HasCreatingEndUserPermission BIT = NULL,
    @HasReadingEndUserPermission BIT = NULL,
    @HasUpdatingEndUserPermission BIT = NULL,
    @HasDeletingEndUserPermission BIT = NULL,
    @HasCreatingEndUserRolePermission BIT = NULL,
    @HasReadingEndUserRolePermission BIT = NULL,
    @HasUpdatingEndUserRolePermission BIT = NULL,
    @HasDeletingEndUserRolePermission BIT = NULL,
    @HasCreatingLocationPermission BIT = NULL,
    @HasReadingLocationPermission BIT = NULL,
    @HasUpdatingLocationPermission BIT = NULL,
    @HasDeletingLocationPermission BIT = NULL,
    @HasCreatingManufacturerPermission BIT = NULL,
    @HasReadingManufacturerPermission BIT = NULL,
    @HasUpdatingManufacturerPermission BIT = NULL,
    @HasDeletingManufacturerPermission BIT = NULL,
    @HasCreatingProductPermission BIT = NULL,
    @HasReadingProductPermission BIT = NULL,
    @HasUpdatingProductPermission BIT = NULL,
    @HasDeletingProductPermission BIT = NULL,
    @HasCreatingProductSetPermission BIT = NULL,
    @HasReadingProductSetPermission BIT = NULL,
    @HasUpdatingProductSetPermission BIT = NULL,
    @HasDeletingProductSetPermission BIT = NULL,
    @HasCreatingRolePermission BIT = NULL,
    @HasReadingRolePermission BIT = NULL,
    @HasUpdatingRolePermission BIT = NULL,
    @HasDeletingRolePermission BIT = NULL,
    @HasReadingStoredProcedureLogPermission BIT = NULL,
    @HasDeletingStoredProcedureLogPermission BIT = NULL,
    @HasCreatingVendorPermission BIT = NULL,
    @HasReadingVendorPermission BIT = NULL,
    @HasUpdatingVendorPermission BIT = NULL,
    @HasDeletingVendorPermission BIT = NULL
AS;
BEGIN
    SET NOCOUNT ON;

    -- Check updating permission of the calling EndUser.
    DECLARE @HasUpdatingEndUserRolePermissionPermission BIT = (SELECT HasUpdatingEndUserRolePermission FROM [dbo].[tvf_GetCRUDPermissionsOfEndUser](@CallingEndUserId));

    IF (@HasUpdatingEndUserRolePermissionPermission IS NULL)
        BEGIN
            RAISERROR ('@CallingEndUserId does not exist!', 11, 0);
            RETURN -1;
        END;
    IF (@HasUpdatingEndUserRolePermissionPermission = 0)
        BEGIN
            RAISERROR ('@CallingEndUserId has no permission to update an EndUserRole!', 11, 0);
            RETURN -1;
        END;

    -- Run actual query.
    UPDATE
        [dbo].[EndUserRole]
    SET
        Name = COALESCE(@Name, Name),
        HasCreatingAssetPermission = COALESCE(@HasCreatingAssetPermission, HasCreatingAssetPermission),
        HasReadingAssetPermission = COALESCE(@HasReadingAssetPermission, HasReadingAssetPermission),
        HasUpdatingAssetPermission = COALESCE(@HasUpdatingAssetPermission, HasUpdatingAssetPermission),
        HasDeletingAssetPermission = COALESCE(@HasDeletingAssetPermission, HasDeletingAssetPermission),
        HasCreatingBuildingPermission = COALESCE(@HasCreatingBuildingPermission, HasCreatingBuildingPermission),
        HasReadingBuildingPermission = COALESCE(@HasReadingBuildingPermission, HasReadingBuildingPermission),
        HasUpdatingBuildingPermission = COALESCE(@HasUpdatingBuildingPermission, HasUpdatingBuildingPermission),
        HasDeletingBuildingPermission = COALESCE(@HasDeletingBuildingPermission, HasDeletingBuildingPermission),
        HasCreatingCategoryPermission = COALESCE(@HasCreatingCategoryPermission, HasCreatingCategoryPermission),
        HasReadingCategoryPermission = COALESCE(@HasReadingCategoryPermission, HasReadingCategoryPermission),
        HasUpdatingCategoryPermission = COALESCE(@HasUpdatingCategoryPermission, HasUpdatingCategoryPermission),
        HasDeletingCategoryPermission = COALESCE(@HasDeletingCategoryPermission, HasDeletingCategoryPermission),
        HasCreatingCompanyPermission = COALESCE(@HasCreatingCompanyPermission, HasCreatingCompanyPermission),
        HasReadingCompanyPermission = COALESCE(@HasReadingCompanyPermission, HasReadingCompanyPermission),
        HasUpdatingCompanyPermission = COALESCE(@HasUpdatingCompanyPermission, HasUpdatingCompanyPermission),
        HasDeletingCompanyPermission = COALESCE(@HasDeletingCompanyPermission, HasDeletingCompanyPermission),
        HasCreatingDepartmentPermission = COALESCE(@HasCreatingDepartmentPermission, HasCreatingDepartmentPermission),
        HasReadingDepartmentPermission = COALESCE(@HasReadingDepartmentPermission, HasReadingDepartmentPermission),
        HasUpdatingDepartmentPermission = COALESCE(@HasUpdatingDepartmentPermission, HasUpdatingDepartmentPermission),
        HasDeletingDepartmentPermission = COALESCE(@HasDeletingDepartmentPermission, HasDeletingDepartmentPermission),
        HasCreatingEmployeePermission = COALESCE(@HasCreatingEmployeePermission, HasCreatingEmployeePermission),
        HasReadingEmployeePermission = COALESCE(@HasReadingEmployeePermission, HasReadingEmployeePermission),
        HasUpdatingEmployeePermission = COALESCE(@HasUpdatingEmployeePermission, HasUpdatingEmployeePermission),
        HasDeletingEmployeePermission = COALESCE(@HasDeletingEmployeePermission, HasDeletingEmployeePermission),
        HasCreatingEndUserPermission = COALESCE(@HasCreatingEndUserPermission, HasCreatingEndUserPermission),
        HasReadingEndUserPermission = COALESCE(@HasReadingEndUserPermission, HasReadingEndUserPermission),
        HasUpdatingEndUserPermission = COALESCE(@HasUpdatingEndUserPermission, HasUpdatingEndUserPermission),
        HasDeletingEndUserPermission = COALESCE(@HasDeletingEndUserPermission, HasDeletingEndUserPermission),
        HasCreatingEndUserRolePermission = COALESCE(@HasCreatingEndUserRolePermission, HasCreatingEndUserRolePermission),
        HasReadingEndUserRolePermission = COALESCE(@HasReadingEndUserRolePermission, HasReadingEndUserRolePermission),
        HasUpdatingEndUserRolePermission = COALESCE(@HasUpdatingEndUserRolePermission, HasUpdatingEndUserRolePermission),
        HasDeletingEndUserRolePermission = COALESCE(@HasDeletingEndUserRolePermission, HasDeletingEndUserRolePermission),
        HasCreatingLocationPermission = COALESCE(@HasCreatingLocationPermission, HasCreatingLocationPermission),
        HasReadingLocationPermission = COALESCE(@HasReadingLocationPermission, HasReadingLocationPermission),
        HasUpdatingLocationPermission = COALESCE(@HasUpdatingLocationPermission, HasUpdatingLocationPermission),
        HasDeletingLocationPermission = COALESCE(@HasDeletingLocationPermission, HasDeletingLocationPermission),
        HasCreatingManufacturerPermission = COALESCE(@HasCreatingManufacturerPermission, HasCreatingManufacturerPermission),
        HasReadingManufacturerPermission = COALESCE(@HasReadingManufacturerPermission, HasReadingManufacturerPermission),
        HasUpdatingManufacturerPermission = COALESCE(@HasUpdatingManufacturerPermission, HasUpdatingManufacturerPermission),
        HasDeletingManufacturerPermission = COALESCE(@HasDeletingManufacturerPermission, HasDeletingManufacturerPermission),
        HasCreatingProductPermission = COALESCE(@HasCreatingProductPermission, HasCreatingProductPermission),
        HasReadingProductPermission = COALESCE(@HasReadingProductPermission, HasReadingProductPermission),
        HasUpdatingProductPermission = COALESCE(@HasUpdatingProductPermission, HasUpdatingProductPermission),
        HasDeletingProductPermission = COALESCE(@HasDeletingProductPermission, HasDeletingProductPermission),
        HasCreatingProductSetPermission = COALESCE(@HasCreatingProductSetPermission, HasCreatingProductSetPermission),
        HasReadingProductSetPermission = COALESCE(@HasReadingProductSetPermission, HasReadingProductSetPermission),
        HasUpdatingProductSetPermission = COALESCE(@HasUpdatingProductSetPermission, HasUpdatingProductSetPermission),
        HasDeletingProductSetPermission = COALESCE(@HasDeletingProductSetPermission, HasDeletingProductSetPermission),
        HasCreatingRolePermission = COALESCE(@HasCreatingRolePermission, HasCreatingRolePermission),
        HasReadingRolePermission = COALESCE(@HasReadingRolePermission, HasReadingRolePermission),
        HasUpdatingRolePermission = COALESCE(@HasUpdatingRolePermission, HasUpdatingRolePermission),
        HasDeletingRolePermission = COALESCE(@HasDeletingRolePermission, HasDeletingRolePermission),
        HasReadingStoredProcedureLogPermission = COALESCE(@HasReadingStoredProcedureLogPermission, HasReadingStoredProcedureLogPermission),
        HasDeletingStoredProcedureLogPermission = COALESCE(@HasDeletingStoredProcedureLogPermission, HasDeletingStoredProcedureLogPermission),
        HasCreatingVendorPermission = COALESCE(@HasCreatingVendorPermission, HasCreatingVendorPermission),
        HasReadingVendorPermission = COALESCE(@HasReadingVendorPermission, HasReadingVendorPermission),
        HasUpdatingVendorPermission = COALESCE(@HasUpdatingVendorPermission, HasUpdatingVendorPermission),
        HasDeletingVendorPermission = COALESCE(@HasDeletingVendorPermission, HasDeletingVendorPermission)
    OUTPUT
        INSERTED.Id,
        INSERTED.Name,
        INSERTED.EndUserRoleCreationDate,
        INSERTED.HasCreatingAssetPermission,
        INSERTED.HasReadingAssetPermission,
        INSERTED.HasUpdatingAssetPermission,
        INSERTED.HasDeletingAssetPermission,
        INSERTED.HasCreatingBuildingPermission,
        INSERTED.HasReadingBuildingPermission,
        INSERTED.HasUpdatingBuildingPermission,
        INSERTED.HasDeletingBuildingPermission,
        INSERTED.HasCreatingCategoryPermission,
        INSERTED.HasReadingCategoryPermission,
        INSERTED.HasUpdatingCategoryPermission,
        INSERTED.HasDeletingCategoryPermission,
        INSERTED.HasCreatingCompanyPermission,
        INSERTED.HasReadingCompanyPermission,
        INSERTED.HasUpdatingCompanyPermission,
        INSERTED.HasDeletingCompanyPermission,
        INSERTED.HasCreatingDepartmentPermission,
        INSERTED.HasReadingDepartmentPermission,
        INSERTED.HasUpdatingDepartmentPermission,
        INSERTED.HasDeletingDepartmentPermission,
        INSERTED.HasCreatingEmployeePermission,
        INSERTED.HasReadingEmployeePermission,
        INSERTED.HasUpdatingEmployeePermission,
        INSERTED.HasDeletingEmployeePermission,
        INSERTED.HasCreatingEndUserPermission,
        INSERTED.HasReadingEndUserPermission,
        INSERTED.HasUpdatingEndUserPermission,
        INSERTED.HasDeletingEndUserPermission,
        INSERTED.HasCreatingEndUserRolePermission,
        INSERTED.HasReadingEndUserRolePermission,
        INSERTED.HasUpdatingEndUserRolePermission,
        INSERTED.HasDeletingEndUserRolePermission,
        INSERTED.HasCreatingLocationPermission,
        INSERTED.HasReadingLocationPermission,
        INSERTED.HasUpdatingLocationPermission,
        INSERTED.HasDeletingLocationPermission,
        INSERTED.HasCreatingManufacturerPermission,
        INSERTED.HasReadingManufacturerPermission,
        INSERTED.HasUpdatingManufacturerPermission,
        INSERTED.HasDeletingManufacturerPermission,
        INSERTED.HasCreatingProductPermission,
        INSERTED.HasReadingProductPermission,
        INSERTED.HasUpdatingProductPermission,
        INSERTED.HasDeletingProductPermission,
        INSERTED.HasCreatingProductSetPermission,
        INSERTED.HasReadingProductSetPermission,
        INSERTED.HasUpdatingProductSetPermission,
        INSERTED.HasDeletingProductSetPermission,
        INSERTED.HasCreatingRolePermission,
        INSERTED.HasReadingRolePermission,
        INSERTED.HasUpdatingRolePermission,
        INSERTED.HasDeletingRolePermission,
        INSERTED.HasReadingStoredProcedureLogPermission,
        INSERTED.HasDeletingStoredProcedureLogPermission,
        INSERTED.HasCreatingVendorPermission,
        INSERTED.HasReadingVendorPermission,
        INSERTED.HasUpdatingVendorPermission,
        INSERTED.HasDeletingVendorPermission,
        DELETED.Name AS OldName,
        DELETED.HasCreatingAssetPermission AS OldHasCreatingAssetPermission,
        DELETED.HasReadingAssetPermission AS OldHasReadingAssetPermission,
        DELETED.HasUpdatingAssetPermission AS OldHasUpdatingAssetPermission,
        DELETED.HasDeletingAssetPermission AS OldHasDeletingAssetPermission,
        DELETED.HasCreatingBuildingPermission AS OldHasCreatingBuildingPermission,
        DELETED.HasReadingBuildingPermission AS OldHasReadingBuildingPermission,
        DELETED.HasUpdatingBuildingPermission AS OldHasUpdatingBuildingPermission,
        DELETED.HasDeletingBuildingPermission AS OldHasDeletingBuildingPermission,
        DELETED.HasCreatingCategoryPermission AS OldHasCreatingCategoryPermission,
        DELETED.HasReadingCategoryPermission AS OldHasReadingCategoryPermission,
        DELETED.HasUpdatingCategoryPermission AS OldHasUpdatingCategoryPermission,
        DELETED.HasDeletingCategoryPermission AS OldHasDeletingCategoryPermission,
        DELETED.HasCreatingCompanyPermission AS OldHasCreatingCompanyPermission,
        DELETED.HasReadingCompanyPermission AS OldHasReadingCompanyPermission,
        DELETED.HasUpdatingCompanyPermission AS OldHasUpdatingCompanyPermission,
        DELETED.HasDeletingCompanyPermission AS OldHasDeletingCompanyPermission,
        DELETED.HasCreatingDepartmentPermission AS OldHasCreatingDepartmentPermission,
        DELETED.HasReadingDepartmentPermission AS OldHasReadingDepartmentPermission,
        DELETED.HasUpdatingDepartmentPermission AS OldHasUpdatingDepartmentPermission,
        DELETED.HasDeletingDepartmentPermission AS OldHasDeletingDepartmentPermission,
        DELETED.HasCreatingEmployeePermission AS OldHasCreatingEmployeePermission,
        DELETED.HasReadingEmployeePermission AS OldHasReadingEmployeePermission,
        DELETED.HasUpdatingEmployeePermission AS OldHasUpdatingEmployeePermission,
        DELETED.HasDeletingEmployeePermission AS OldHasDeletingEmployeePermission,
        DELETED.HasCreatingEndUserPermission AS OldHasCreatingEndUserPermission,
        DELETED.HasReadingEndUserPermission AS OldHasReadingEndUserPermission,
        DELETED.HasUpdatingEndUserPermission AS OldHasUpdatingEndUserPermission,
        DELETED.HasDeletingEndUserPermission AS OldHasDeletingEndUserPermission,
        DELETED.HasCreatingEndUserRolePermission AS OldHasCreatingEndUserRolePermission,
        DELETED.HasReadingEndUserRolePermission AS OldHasReadingEndUserRolePermission,
        DELETED.HasUpdatingEndUserRolePermission AS OldHasUpdatingEndUserRolePermission,
        DELETED.HasDeletingEndUserRolePermission AS OldHasDeletingEndUserRolePermission,
        DELETED.HasCreatingLocationPermission AS OldHasCreatingLocationPermission,
        DELETED.HasReadingLocationPermission AS OldHasReadingLocationPermission,
        DELETED.HasUpdatingLocationPermission AS OldHasUpdatingLocationPermission,
        DELETED.HasDeletingLocationPermission AS OldHasDeletingLocationPermission,
        DELETED.HasCreatingManufacturerPermission AS OldHasCreatingManufacturerPermission,
        DELETED.HasReadingManufacturerPermission AS OldHasReadingManufacturerPermission,
        DELETED.HasUpdatingManufacturerPermission AS OldHasUpdatingManufacturerPermission,
        DELETED.HasDeletingManufacturerPermission AS OldHasDeletingManufacturerPermission,
        DELETED.HasCreatingProductPermission AS OldHasCreatingProductPermission,
        DELETED.HasReadingProductPermission AS OldHasReadingProductPermission,
        DELETED.HasUpdatingProductPermission AS OldHasUpdatingProductPermission,
        DELETED.HasDeletingProductPermission AS OldHasDeletingProductPermission,
        DELETED.HasCreatingProductSetPermission AS OldHasCreatingProductSetPermission,
        DELETED.HasReadingProductSetPermission AS OldHasReadingProductSetPermission,
        DELETED.HasUpdatingProductSetPermission AS OldHasUpdatingProductSetPermission,
        DELETED.HasDeletingProductSetPermission AS OldHasDeletingProductSetPermission,
        DELETED.HasCreatingRolePermission AS OldHasCreatingRolePermission,
        DELETED.HasReadingRolePermission AS OldHasReadingRolePermission,
        DELETED.HasUpdatingRolePermission AS OldHasUpdatingRolePermission,
        DELETED.HasDeletingRolePermission AS OldHasDeletingRolePermission,
        DELETED.HasReadingStoredProcedureLogPermission AS OldHasReadingStoredProcedureLogPermission,
        DELETED.HasDeletingStoredProcedureLogPermission AS OldHasDeletingStoredProcedureLogPermission,
        DELETED.HasCreatingVendorPermission AS OldHasCreatingVendorPermission,
        DELETED.HasReadingVendorPermission AS OldHasReadingVendorPermission,
        DELETED.HasUpdatingVendorPermission AS OldHasUpdatingVendorPermission,
        DELETED.HasDeletingVendorPermission AS OldHasDeletingVendorPermission
    FROM
        [dbo].[EndUserRole]
    WHERE
        Id = @Id;
END;
