CREATE PROCEDURE [dbo].[usp_UpdateEndUserRole]
    @CallingEndUserID UNIQUEIDENTIFIER,
    @EndUserRoleID UNIQUEIDENTIFIER,
    @EndUserRoleName NVARCHAR(850) = NULL,
    @CreateAsset BIT = NULL,
    @ReadAsset BIT = NULL,
    @UpdateAsset BIT = NULL,
    @DeleteAsset BIT = NULL,
    @CreateAssetFix BIT = NULL,
    @ReadAssetFix BIT = NULL,
    @UpdateAssetFix BIT = NULL,
    @DeleteAssetFix BIT = NULL,
    @CreateAssetIssue BIT = NULL,
    @ReadAssetIssue BIT = NULL,
    @UpdateAssetIssue BIT = NULL,
    @DeleteAssetIssue BIT = NULL,
    @CreateAssetTransfer BIT = NULL,
    @ReadAssetTransfer BIT = NULL,
    @UpdateAssetTransfer BIT = NULL,
    @DeleteAssetTransfer BIT = NULL,
    @CreateBuilding BIT = NULL,
    @ReadBuilding BIT = NULL,
    @UpdateBuilding BIT = NULL,
    @DeleteBuilding BIT = NULL,
    @CreateCategory BIT = NULL,
    @ReadCategory BIT = NULL,
    @UpdateCategory BIT = NULL,
    @DeleteCategory BIT = NULL,
    @CreateCompany BIT = NULL,
    @ReadCompany BIT = NULL,
    @UpdateCompany BIT = NULL,
    @DeleteCompany BIT = NULL,
    @CreateDepartment BIT = NULL,
    @ReadDepartment BIT = NULL,
    @UpdateDepartment BIT = NULL,
    @DeleteDepartment BIT = NULL,
    @CreateEmployee BIT = NULL,
    @ReadEmployee BIT = NULL,
    @UpdateEmployee BIT = NULL,
    @DeleteEmployee BIT = NULL,
    @CreateEndUser BIT = NULL,
    @ReadEndUser BIT = NULL,
    @UpdateEndUser BIT = NULL,
    @DeleteEndUser BIT = NULL,
    @CreateEndUserRole BIT = NULL,
    @ReadEndUserRole BIT = NULL,
    @UpdateEndUserRole BIT = NULL,
    @DeleteEndUserRole BIT = NULL,
    @CreateLocation BIT = NULL,
    @ReadLocation BIT = NULL,
    @UpdateLocation BIT = NULL,
    @DeleteLocation BIT = NULL,
    @ReadLog BIT = NULL,
    @DeleteLog BIT = NULL,
    @CreateManufacturer BIT = NULL,
    @ReadManufacturer BIT = NULL,
    @UpdateManufacturer BIT = NULL,
    @DeleteManufacturer BIT = NULL,
    @CreateProduct BIT = NULL,
    @ReadProduct BIT = NULL,
    @UpdateProduct BIT = NULL,
    @DeleteProduct BIT = NULL,
    @CreateProductSet BIT = NULL,
    @ReadProductSet BIT = NULL,
    @UpdateProductSet BIT = NULL,
    @DeleteProductSet BIT = NULL,
    @CreateRole BIT = NULL,
    @ReadRole BIT = NULL,
    @UpdateRole BIT = NULL,
    @DeleteRole BIT = NULL,
    @CreateVendor BIT = NULL,
    @ReadVendor BIT = NULL,
    @UpdateVendor BIT = NULL,
    @DeleteVendor BIT = NULL
AS;
BEGIN
    SET NOCOUNT ON;

    -- Check updating permission of the calling EndUser.
    DECLARE @UpdateEndUserRolePermission BIT = (SELECT UpdateEndUserRole FROM [dbo].[tvf_GetCRUDPermissionsOfEndUser](@CallingEndUserID));

    IF (@UpdateEndUserRolePermission IS NULL)
        BEGIN
            RAISERROR ('@CallingEndUserID does not exist!', 11, 0);
            RETURN -1;
        END;
    IF (@UpdateEndUserRolePermission = 0)
        BEGIN
            RAISERROR ('@CallingEndUserID has no permission to update an EndUserRole!', 11, 0);
            RETURN -1;
        END;

    -- Run actual query.
    UPDATE
        [dbo].[EndUserRole]
    SET
        EndUserRoleName = ISNULL(@EndUserRoleName, EndUserRoleName),
        CreateAsset = ISNULL(@CreateAsset, CreateAsset),
        ReadAsset = ISNULL(@ReadAsset, ReadAsset),
        UpdateAsset = ISNULL(@UpdateAsset, UpdateAsset),
        DeleteAsset = ISNULL(@DeleteAsset, DeleteAsset),
        CreateAssetFix = ISNULL(@CreateAssetFix, CreateAssetFix),
        ReadAssetFix = ISNULL(@ReadAssetFix, ReadAssetFix),
        UpdateAssetFix = ISNULL(@UpdateAssetFix, UpdateAssetFix),
        DeleteAssetFix = ISNULL(@DeleteAssetFix, DeleteAssetFix),
        CreateAssetIssue = ISNULL(@CreateAssetIssue, CreateAssetIssue),
        ReadAssetIssue = ISNULL(@ReadAssetIssue, ReadAssetIssue),
        UpdateAssetIssue = ISNULL(@UpdateAssetIssue, UpdateAssetIssue),
        DeleteAssetIssue = ISNULL(@DeleteAssetIssue, DeleteAssetIssue),
        CreateAssetTransfer = ISNULL(@CreateAssetTransfer, CreateAssetTransfer),
        ReadAssetTransfer = ISNULL(@ReadAssetTransfer, ReadAssetTransfer),
        UpdateAssetTransfer = ISNULL(@UpdateAssetTransfer, UpdateAssetTransfer),
        DeleteAssetTransfer = ISNULL(@DeleteAssetTransfer, DeleteAssetTransfer),
        CreateBuilding = ISNULL(@CreateBuilding, CreateBuilding),
        ReadBuilding = ISNULL(@ReadBuilding, ReadBuilding),
        UpdateBuilding = ISNULL(@UpdateBuilding, UpdateBuilding),
        DeleteBuilding = ISNULL(@DeleteBuilding, DeleteBuilding),
        CreateCategory = ISNULL(@CreateCategory, CreateCategory),
        ReadCategory = ISNULL(@ReadCategory, ReadCategory),
        UpdateCategory = ISNULL(@UpdateCategory, UpdateCategory),
        DeleteCategory = ISNULL(@DeleteCategory, DeleteCategory),
        CreateCompany = ISNULL(@CreateCompany, CreateCompany),
        ReadCompany = ISNULL(@ReadCompany, ReadCompany),
        UpdateCompany = ISNULL(@UpdateCompany, UpdateCompany),
        DeleteCompany = ISNULL(@DeleteCompany, DeleteCompany),
        CreateDepartment = ISNULL(@CreateDepartment, CreateDepartment),
        ReadDepartment = ISNULL(@ReadDepartment, ReadDepartment),
        UpdateDepartment = ISNULL(@UpdateDepartment, UpdateDepartment),
        DeleteDepartment = ISNULL(@DeleteDepartment, DeleteDepartment),
        CreateEmployee = ISNULL(@CreateEmployee, CreateEmployee),
        ReadEmployee = ISNULL(@ReadEmployee, ReadEmployee),
        UpdateEmployee = ISNULL(@UpdateEmployee, UpdateEmployee),
        DeleteEmployee = ISNULL(@DeleteEmployee, DeleteEmployee),
        CreateEndUser = ISNULL(@CreateEndUser, CreateEndUser),
        ReadEndUser = ISNULL(@ReadEndUser, ReadEndUser),
        UpdateEndUser = ISNULL(@UpdateEndUser, UpdateEndUser),
        DeleteEndUser = ISNULL(@DeleteEndUser, DeleteEndUser),
        CreateEndUserRole = ISNULL(@CreateEndUserRole, CreateEndUserRole),
        ReadEndUserRole = ISNULL(@ReadEndUserRole, ReadEndUserRole),
        UpdateEndUserRole = ISNULL(@UpdateEndUserRole, UpdateEndUserRole),
        DeleteEndUserRole = ISNULL(@DeleteEndUserRole, DeleteEndUserRole),
        CreateLocation = ISNULL(@CreateLocation, CreateLocation),
        ReadLocation = ISNULL(@ReadLocation, ReadLocation),
        UpdateLocation = ISNULL(@UpdateLocation, UpdateLocation),
        DeleteLocation = ISNULL(@DeleteLocation, DeleteLocation),
        ReadLog = ISNULL(@ReadLog, @ReadLog),
        DeleteLog = ISNULL(@DeleteLog, @DeleteLog),
        CreateManufacturer = ISNULL(@CreateManufacturer, CreateManufacturer),
        ReadManufacturer = ISNULL(@ReadManufacturer, ReadManufacturer),
        UpdateManufacturer = ISNULL(@UpdateManufacturer, UpdateManufacturer),
        DeleteManufacturer = ISNULL(@DeleteManufacturer, DeleteManufacturer),
        CreateProduct = ISNULL(@CreateProduct, CreateProduct),
        ReadProduct = ISNULL(@ReadProduct, ReadProduct),
        UpdateProduct = ISNULL(@UpdateProduct, UpdateProduct),
        DeleteProduct = ISNULL(@DeleteProduct, DeleteProduct),
        CreateProductSet = ISNULL(@CreateProductSet, CreateProductSet),
        ReadProductSet = ISNULL(@ReadProductSet, ReadProductSet),
        UpdateProductSet = ISNULL(@UpdateProductSet, UpdateProductSet),
        DeleteProductSet = ISNULL(@DeleteProductSet, DeleteProductSet),
        CreateRole = ISNULL(@CreateRole, CreateRole),
        ReadRole = ISNULL(@ReadRole, ReadRole),
        UpdateRole = ISNULL(@UpdateRole, UpdateRole),
        DeleteRole = ISNULL(@DeleteRole, DeleteRole),
        CreateVendor = ISNULL(@CreateVendor, CreateVendor),
        ReadVendor = ISNULL(@ReadVendor, ReadVendor),
        UpdateVendor = ISNULL(@UpdateVendor, UpdateVendor),
        DeleteVendor = ISNULL(@DeleteVendor, DeleteVendor)
    OUTPUT
        INSERTED.EndUserRoleID,
        INSERTED.EndUserRoleName,
        INSERTED.EndUserRoleCreationDate,
        INSERTED.CreateAsset,
        INSERTED.ReadAsset,
        INSERTED.UpdateAsset,
        INSERTED.DeleteAsset,
        INSERTED.CreateAssetFix,
        INSERTED.ReadAssetFix,
        INSERTED.UpdateAssetFix,
        INSERTED.DeleteAssetFix,
        INSERTED.CreateAssetIssue,
        INSERTED.ReadAssetIssue,
        INSERTED.UpdateAssetIssue,
        INSERTED.DeleteAssetIssue,
        INSERTED.CreateAssetTransfer,
        INSERTED.ReadAssetTransfer,
        INSERTED.UpdateAssetTransfer,
        INSERTED.DeleteAssetTransfer,
        INSERTED.CreateBuilding,
        INSERTED.ReadBuilding,
        INSERTED.UpdateBuilding,
        INSERTED.DeleteBuilding,
        INSERTED.CreateCategory,
        INSERTED.ReadCategory,
        INSERTED.UpdateCategory,
        INSERTED.DeleteCategory,
        INSERTED.CreateCompany,
        INSERTED.ReadCompany,
        INSERTED.UpdateCompany,
        INSERTED.DeleteCompany,
        INSERTED.CreateDepartment,
        INSERTED.ReadDepartment,
        INSERTED.UpdateDepartment,
        INSERTED.DeleteDepartment,
        INSERTED.CreateEmployee,
        INSERTED.ReadEmployee,
        INSERTED.UpdateEmployee,
        INSERTED.DeleteEmployee,
        INSERTED.CreateEndUser,
        INSERTED.ReadEndUser,
        INSERTED.UpdateEndUser,
        INSERTED.DeleteEndUser,
        INSERTED.CreateEndUserRole,
        INSERTED.ReadEndUserRole,
        INSERTED.UpdateEndUserRole,
        INSERTED.DeleteEndUserRole,
        INSERTED.CreateLocation,
        INSERTED.ReadLocation,
        INSERTED.UpdateLocation,
        INSERTED.DeleteLocation,
        INSERTED.ReadLog,
        INSERTED.DeleteLog,
        INSERTED.CreateManufacturer,
        INSERTED.ReadManufacturer,
        INSERTED.UpdateManufacturer,
        INSERTED.DeleteManufacturer,
        INSERTED.CreateProduct,
        INSERTED.ReadProduct,
        INSERTED.UpdateProduct,
        INSERTED.DeleteProduct,
        INSERTED.CreateProductSet,
        INSERTED.ReadProductSet,
        INSERTED.UpdateProductSet,
        INSERTED.DeleteProductSet,
        INSERTED.CreateRole,
        INSERTED.ReadRole,
        INSERTED.UpdateRole,
        INSERTED.DeleteRole,
        INSERTED.CreateVendor,
        INSERTED.ReadVendor,
        INSERTED.UpdateVendor,
        INSERTED.DeleteVendor,
        DELETED.EndUserRoleName AS OldEndUserRoleName,
        DELETED.CreateAsset AS OldCreateAsset,
        DELETED.ReadAsset AS OldReadAsset,
        DELETED.UpdateAsset AS OldUpdateAsset,
        DELETED.DeleteAsset AS OldDeleteAsset,
        DELETED.CreateAssetFix AS OldCreateAssetFix,
        DELETED.ReadAssetFix AS OldReadAssetFix,
        DELETED.UpdateAssetFix AS OldUpdateAssetFix,
        DELETED.DeleteAssetFix AS OldDeleteAssetFix,
        DELETED.CreateAssetIssue AS OldCreateAssetIssue,
        DELETED.ReadAssetIssue AS OldReadAssetIssue,
        DELETED.UpdateAssetIssue AS OldUpdateAssetIssue,
        DELETED.DeleteAssetIssue AS OldDeleteAssetIssue,
        DELETED.CreateAssetTransfer AS OldCreateAssetTransfer,
        DELETED.ReadAssetTransfer AS OldReadAssetTransfer,
        DELETED.UpdateAssetTransfer AS OldUpdateAssetTransfer,
        DELETED.DeleteAssetTransfer AS OldDeleteAssetTransfer,
        DELETED.CreateBuilding AS OldCreateBuilding,
        DELETED.ReadBuilding AS OldReadBuilding,
        DELETED.UpdateBuilding AS OldUpdateBuilding,
        DELETED.DeleteBuilding AS OldDeleteBuilding,
        DELETED.CreateCategory AS OldCreateCategory,
        DELETED.ReadCategory AS OldReadCategory,
        DELETED.UpdateCategory AS OldUpdateCategory,
        DELETED.DeleteCategory AS OldDeleteCategory,
        DELETED.CreateCompany AS OldCreateCompany,
        DELETED.ReadCompany AS OldReadCompany,
        DELETED.UpdateCompany AS OldUpdateCompany,
        DELETED.DeleteCompany AS OldDeleteCompany,
        DELETED.CreateDepartment AS OldCreateDepartment,
        DELETED.ReadDepartment AS OldReadDepartment,
        DELETED.UpdateDepartment AS OldUpdateDepartment,
        DELETED.DeleteDepartment AS OldDeleteDepartment,
        DELETED.CreateEmployee AS OldCreateEmployee,
        DELETED.ReadEmployee AS OldReadEmployee,
        DELETED.UpdateEmployee AS OldUpdateEmployee,
        DELETED.DeleteEmployee AS OldDeleteEmployee,
        DELETED.CreateEndUser AS OldCreateEndUser,
        DELETED.ReadEndUser AS OldReadEndUser,
        DELETED.UpdateEndUser AS OldUpdateEndUser,
        DELETED.DeleteEndUser AS OldDeleteEndUser,
        DELETED.CreateEndUserRole AS OldCreateEndUserRole,
        DELETED.ReadEndUserRole AS OldReadEndUserRole,
        DELETED.UpdateEndUserRole AS OldUpdateEndUserRole,
        DELETED.DeleteEndUserRole AS OldDeleteEndUserRole,
        DELETED.CreateLocation AS OldCreateLocation,
        DELETED.ReadLocation AS OldReadLocation,
        DELETED.UpdateLocation AS OldUpdateLocation,
        DELETED.DeleteLocation AS OldDeleteLocation,
        DELETED.ReadLog AS OldReadLog,
        DELETED.DeleteLog AS OldDeleteLog,
        DELETED.CreateManufacturer AS OldCreateManufacturer,
        DELETED.ReadManufacturer AS OldReadManufacturer,
        DELETED.UpdateManufacturer AS OldUpdateManufacturer,
        DELETED.DeleteManufacturer AS OldDeleteManufacturer,
        DELETED.CreateProduct AS OldCreateProduct,
        DELETED.ReadProduct AS OldReadProduct,
        DELETED.UpdateProduct AS OldUpdateProduct,
        DELETED.DeleteProduct AS OldDeleteProduct,
        DELETED.CreateProductSet AS OldCreateProductSet,
        DELETED.ReadProductSet AS OldReadProductSet,
        DELETED.UpdateProductSet AS OldUpdateProductSet,
        DELETED.DeleteProductSet AS OldDeleteProductSet,
        DELETED.CreateRole AS OldCreateRole,
        DELETED.ReadRole AS OldReadRole,
        DELETED.UpdateRole AS OldUpdateRole,
        DELETED.DeleteRole AS OldDeleteRole,
        DELETED.CreateVendor AS OldCreateVendor,
        DELETED.ReadVendor AS OldReadVendor,
        DELETED.UpdateVendor AS OldUpdateVendor,
        DELETED.DeleteVendor AS OldDeleteVendor
    FROM
        [dbo].[EndUserRole]
    WHERE
        EndUserRoleID = @EndUserRoleID;
END;
