CREATE PROCEDURE [dbo].[usp_CreateEndUserRole]
    @CallingEndUserID UNIQUEIDENTIFIER,
    @Name NVARCHAR(850),
    @HasCreatingAssetPermission BIT = NULL,
    @HasReadingAssetPermission BIT = NULL,
    @HasUpdatingAssetPermission BIT = NULL,
    @HasDeletingAssetPermission BIT = NULL,
    @HasCreatingAssetFixPermission BIT = NULL,
    @HasReadingAssetFixPermission BIT = NULL,
    @HasUpdatingAssetFixPermission BIT = NULL,
    @HasDeletingAssetFixPermission BIT = NULL,
    @HasCreatingAssetIssuePermission BIT = NULL,
    @HasReadingAssetIssuePermission BIT = NULL,
    @HasUpdatingAssetIssuePermission BIT = NULL,
    @HasDeletingAssetIssuePermission BIT = NULL,
    @HasCreatingBuildingPermission BIT = NULL,
    @HasReadingBuildingPermission BIT = NULL,
    @HasUpdatingBuildingPermission BIT = NULL,
    @HasDeletingBuildingPermission BIT = NULL,
    @HasCreatingCategoryPermission BIT = NULL,
    @HasReadingCategoryPermission BIT = NULL,
    @HasUpdatingCategoryPermission BIT = NULL,
    @HasDeletingCategoryPermission BIT = NULL,
    @HasCreatingCompanyPermission BIT = NULL,
    @HasReadingCompanyPermission BIT = NULL,
    @HasUpdatingCompanyPermission BIT = NULL,
    @HasDeletingCompanyPermission BIT = NULL,
    @HasCreatingDepartmentPermission BIT = NULL,
    @HasReadingDepartmentPermission BIT = NULL,
    @HasUpdatingDepartmentPermission BIT = NULL,
    @HasDeletingDepartmentPermission BIT = NULL,
    @HasCreatingEmployeePermission BIT = NULL,
    @HasReadingEmployeePermission BIT = NULL,
    @HasUpdatingEmployeePermission BIT = NULL,
    @HasDeletingEmployeePermission BIT = NULL,
    @HasCreatingEndUserPermission BIT = NULL,
    @HasReadingEndUserPermission BIT = NULL,
    @HasUpdatingEndUserPermission BIT = NULL,
    @HasDeletingEndUserPermission BIT = NULL,
    @HasCreatingEndUserRolePermission BIT = NULL,
    @HasReadingEndUserRolePermission BIT = NULL,
    @HasUpdatingEndUserRolePermission BIT = NULL,
    @HasDeletingEndUserRolePermission BIT = NULL,
    @HasCreatingLocationPermission BIT = NULL,
    @HasReadingLocationPermission BIT = NULL,
    @HasUpdatingLocationPermission BIT = NULL,
    @HasDeletingLocationPermission BIT = NULL,
    @HasCreatingManufacturerPermission BIT = NULL,
    @HasReadingManufacturerPermission BIT = NULL,
    @HasUpdatingManufacturerPermission BIT = NULL,
    @HasDeletingManufacturerPermission BIT = NULL,
    @HasCreatingProductPermission BIT = NULL,
    @HasReadingProductPermission BIT = NULL,
    @HasUpdatingProductPermission BIT = NULL,
    @HasDeletingProductPermission BIT = NULL,
    @HasCreatingProductSetPermission BIT = NULL,
    @HasReadingProductSetPermission BIT = NULL,
    @HasUpdatingProductSetPermission BIT = NULL,
    @HasDeletingProductSetPermission BIT = NULL,
    @HasCreatingRolePermission BIT = NULL,
    @HasReadingRolePermission BIT = NULL,
    @HasUpdatingRolePermission BIT = NULL,
    @HasDeletingRolePermission BIT = NULL,
    @HasReadingStoredProcedureLogPermission BIT = NULL,
    @HasDeletingStoredProcedureLogPermission BIT = NULL,
    @HasCreatingVendorPermission BIT = NULL,
    @HasReadingVendorPermission BIT = NULL,
    @HasUpdatingVendorPermission BIT = NULL,
    @HasDeletingVendorPermission BIT = NULL
AS;
BEGIN
    SET NOCOUNT ON;

    -- Check creating permission of the calling EndUser.
    DECLARE @HasCreatingEndUserRolePermissionBIT = (SELECT HasCreatingEndUserRolePermission FROM [dbo].[tvf_GetCRUDPermissionsOfEndUser](@CallingEndUserID));

    IF (@HasCreatingEndUserRolePermissionIS NULL)
        BEGIN
            RAISERROR ('@CallingEndUserID does not exist!', 11, 0);
            RETURN -1;
        END;
    IF (@HasCreatingEndUserRolePermission= 0)
        BEGIN
            RAISERROR ('@CallingEndUserID has no permission to create an EndUserRole!', 11, 0);
            RETURN -1;
        END;

    -- Run actual query.
    INSERT INTO [dbo].[EndUserRole] (
        Name,
        HasCreatingAssetPermission,
        HasReadingAssetPermission,
        HasUpdatingAssetPermission,
        HasDeletingAssetPermission,
        HasCreatingAssetFixPermission,
        HasReadingAssetFixPermission,
        HasUpdatingAssetFixPermission,
        HasDeletingAssetFixPermission,
        HasCreatingAssetIssuePermission,
        HasReadingAssetIssuePermission,
        HasUpdatingAssetIssuePermission,
        HasDeletingAssetIssuePermission,
        HasCreatingBuildingPermission,
        HasReadingBuildingPermission,
        HasUpdatingBuildingPermission,
        HasDeletingBuildingPermission,
        HasCreatingCategoryPermission,
        HasReadingCategoryPermission,
        HasUpdatingCategoryPermission,
        HasDeletingCategoryPermission,
        HasCreatingCompanyPermission,
        HasReadingCompanyPermission,
        HasUpdatingCompanyPermission,
        HasDeletingCompanyPermission,
        HasCreatingDepartmentPermission,
        HasReadingDepartmentPermission,
        HasUpdatingDepartmentPermission,
        HasDeletingDepartmentPermission,
        HasCreatingEmployeePermission,
        HasReadingEmployeePermission,
        HasUpdatingEmployeePermission,
        HasDeletingEmployeePermission,
        HasCreatingEndUserPermission,
        HasReadingEndUserPermission,
        HasUpdatingEndUserPermission,
        HasDeletingEndUserPermission,
        HasCreatingEndUserRolePermission,
        HasReadingEndUserRolePermission,
        HasUpdatingEndUserRolePermission,
        HasDeletingEndUserRolePermission,
        HasCreatingLocationPermission,
        HasReadingLocationPermission,
        HasUpdatingLocationPermission,
        HasDeletingLocationPermission,
        HasCreatingManufacturerPermission,
        HasReadingManufacturerPermission,
        HasUpdatingManufacturerPermission,
        HasDeletingManufacturerPermission,
        HasCreatingProductPermission,
        HasReadingProductPermission,
        HasUpdatingProductPermission,
        HasDeletingProductPermission,
        HasCreatingProductSetPermission,
        HasReadingProductSetPermission,
        HasUpdatingProductSetPermission,
        HasDeletingProductSetPermission,
        HasCreatingRolePermission,
        HasReadingRolePermission,
        HasUpdatingRolePermission,
        HasDeletingRolePermission,
        HasReadingStoredProcedureLogPermission,
        HasDeletingStoredProcedureLogPermission,
        HasCreatingVendorPermission,
        HasReadingVendorPermission,
        HasUpdatingVendorPermission,
        HasDeletingVendorPermission
    )
    OUTPUT
        INSERTED.Id,
        INSERTED.Name,
        INSERTED.EndUserRoleCreationDate,
        INSERTED.HasCreatingAssetPermission,
        INSERTED.HasReadingAssetPermission,
        INSERTED.HasUpdatingAssetPermission,
        INSERTED.HasDeletingAssetPermission,
        INSERTED.HasCreatingAssetFixPermission,
        INSERTED.HasReadingAssetFixPermission,
        INSERTED.HasUpdatingAssetFixPermission,
        INSERTED.HasDeletingAssetFixPermission,
        INSERTED.HasCreatingAssetIssuePermission,
        INSERTED.HasReadingAssetIssuePermission,
        INSERTED.HasUpdatingAssetIssuePermission,
        INSERTED.HasDeletingAssetIssuePermission,
        INSERTED.HasCreatingBuildingPermission,
        INSERTED.HasReadingBuildingPermission,
        INSERTED.HasUpdatingBuildingPermission,
        INSERTED.HasDeletingBuildingPermission,
        INSERTED.HasCreatingCategoryPermission,
        INSERTED.HasReadingCategoryPermission,
        INSERTED.HasUpdatingCategoryPermission,
        INSERTED.HasDeletingCategoryPermission,
        INSERTED.HasCreatingCompanyPermission,
        INSERTED.HasReadingCompanyPermission,
        INSERTED.HasUpdatingCompanyPermission,
        INSERTED.HasDeletingCompanyPermission,
        INSERTED.HasCreatingDepartmentPermission,
        INSERTED.HasReadingDepartmentPermission,
        INSERTED.HasUpdatingDepartmentPermission,
        INSERTED.HasDeletingDepartmentPermission,
        INSERTED.HasCreatingEmployeePermission,
        INSERTED.HasReadingEmployeePermission,
        INSERTED.HasUpdatingEmployeePermission,
        INSERTED.HasDeletingEmployeePermission,
        INSERTED.HasCreatingEndUserPermission,
        INSERTED.HasReadingEndUserPermission,
        INSERTED.HasUpdatingEndUserPermission,
        INSERTED.HasDeletingEndUserPermission,
        INSERTED.HasCreatingEndUserRolePermission,
        INSERTED.HasReadingEndUserRolePermission,
        INSERTED.HasUpdatingEndUserRolePermission,
        INSERTED.HasDeletingEndUserRolePermission,
        INSERTED.HasCreatingLocationPermission,
        INSERTED.HasReadingLocationPermission,
        INSERTED.HasUpdatingLocationPermission,
        INSERTED.HasDeletingLocationPermission,
        INSERTED.HasCreatingManufacturerPermission,
        INSERTED.HasReadingManufacturerPermission,
        INSERTED.HasUpdatingManufacturerPermission,
        INSERTED.HasDeletingManufacturerPermission,
        INSERTED.HasCreatingProductPermission,
        INSERTED.HasReadingProductPermission,
        INSERTED.HasUpdatingProductPermission,
        INSERTED.HasDeletingProductPermission,
        INSERTED.HasCreatingProductSetPermission,
        INSERTED.HasReadingProductSetPermission,
        INSERTED.HasUpdatingProductSetPermission,
        INSERTED.HasDeletingProductSetPermission,
        INSERTED.HasCreatingRolePermission,
        INSERTED.HasReadingRolePermission,
        INSERTED.HasUpdatingRolePermission,
        INSERTED.HasDeletingRolePermission,
        INSERTED.HasReadingStoredProcedureLogPermission,
        INSERTED.HasDeletingStoredProcedureLogPermission,
        INSERTED.HasCreatingVendorPermission,
        INSERTED.HasReadingVendorPermission,
        INSERTED.HasUpdatingVendorPermission,
        INSERTED.HasDeletingVendorPermission
    VALUES (
        @Name,
        ISNULL(@HasCreatingAssetPermission, 0),
        ISNULL(@HasReadingAssetPermission, 0),
        ISNULL(@HasUpdatingAssetPermission, 0),
        ISNULL(@HasDeletingAssetPermission, 0),
        ISNULL(@HasCreatingAssetFixPermission, 0),
        ISNULL(@HasReadingAssetFixPermission, 0),
        ISNULL(@HasUpdatingAssetFixPermission, 0),
        ISNULL(@HasDeletingAssetFixPermission, 0),
        ISNULL(@HasCreatingAssetIssuePermission, 0),
        ISNULL(@HasReadingAssetIssuePermission, 0),
        ISNULL(@HasUpdatingAssetIssuePermission, 0),
        ISNULL(@HasDeletingAssetIssuePermission, 0),
        ISNULL(@HasCreatingBuildingPermission, 0),
        ISNULL(@HasReadingBuildingPermission, 0),
        ISNULL(@HasUpdatingBuildingPermission, 0),
        ISNULL(@HasDeletingBuildingPermission, 0),
        ISNULL(@HasCreatingCategoryPermission, 0),
        ISNULL(@HasReadingCategoryPermission, 0),
        ISNULL(@HasUpdatingCategoryPermission, 0),
        ISNULL(@HasDeletingCategoryPermission, 0),
        ISNULL(@HasCreatingCompanyPermission, 0),
        ISNULL(@HasReadingCompanyPermission, 0),
        ISNULL(@HasUpdatingCompanyPermission, 0),
        ISNULL(@HasDeletingCompanyPermission, 0),
        ISNULL(@HasCreatingDepartmentPermission, 0),
        ISNULL(@HasReadingDepartmentPermission, 0),
        ISNULL(@HasUpdatingDepartmentPermission, 0),
        ISNULL(@HasDeletingDepartmentPermission, 0),
        ISNULL(@HasCreatingEmployeePermission, 0),
        ISNULL(@HasReadingEmployeePermission, 0),
        ISNULL(@HasUpdatingEmployeePermission, 0),
        ISNULL(@HasDeletingEmployeePermission, 0),
        ISNULL(@HasCreatingEndUserPermission, 0),
        ISNULL(@HasReadingEndUserPermission, 0),
        ISNULL(@HasUpdatingEndUserPermission, 0),
        ISNULL(@HasDeletingEndUserPermission, 0),
        ISNULL(@HasCreatingEndUserRolePermission, 0),
        ISNULL(@HasReadingEndUserRolePermission, 0),
        ISNULL(@HasUpdatingEndUserRolePermission, 0),
        ISNULL(@HasDeletingEndUserRolePermission, 0),
        ISNULL(@HasCreatingLocationPermission, 0),
        ISNULL(@HasReadingLocationPermission, 0),
        ISNULL(@HasUpdatingLocationPermission, 0),
        ISNULL(@HasDeletingLocationPermission, 0),
        ISNULL(@HasCreatingManufacturerPermission, 0),
        ISNULL(@HasReadingManufacturerPermission, 0),
        ISNULL(@HasUpdatingManufacturerPermission, 0),
        ISNULL(@HasDeletingManufacturerPermission, 0),
        ISNULL(@HasCreatingProductPermission, 0),
        ISNULL(@HasReadingProductPermission, 0),
        ISNULL(@HasUpdatingProductPermission, 0),
        ISNULL(@HasDeletingProductPermission, 0),
        ISNULL(@HasCreatingProductSetPermission, 0),
        ISNULL(@HasReadingProductSetPermission, 0),
        ISNULL(@HasUpdatingProductSetPermission, 0),
        ISNULL(@HasDeletingProductSetPermission, 0),
        ISNULL(@HasCreatingRolePermission, 0),
        ISNULL(@HasReadingRolePermission, 0),
        ISNULL(@HasUpdatingRolePermission, 0),
        ISNULL(@HasDeletingRolePermission, 0),
        ISNULL(@HasReadingStoredProcedureLogPermission, 0),
        ISNULL(@HasDeletingStoredProcedureLogPermission, 0),
        ISNULL(@HasCreatingVendorPermission, 0),
        ISNULL(@HasReadingVendorPermission, 0),
        ISNULL(@HasUpdatingVendorPermission, 0),
        ISNULL(@HasDeletingVendorPermission, 0)
    );
END;
