CREATE PROCEDURE [dbo].[usp_CreateEndUserRole]
    @CallingEndUserId UNIQUEIDENTIFIER,
    @Name NVARCHAR(850),
    @HasCreatingAssetPermission BIT = NULL,
    @HasReadingAssetPermission BIT = NULL,
    @HasUpdatingAssetPermission BIT = NULL,
    @HasDeletingAssetPermission BIT = NULL,
    @HasCreatingBuildingPermission BIT = NULL,
    @HasReadingBuildingPermission BIT = NULL,
    @HasUpdatingBuildingPermission BIT = NULL,
    @HasDeletingBuildingPermission BIT = NULL,
    @HasCreatingCategoryPermission BIT = NULL,
    @HasReadingCategoryPermission BIT = NULL,
    @HasUpdatingCategoryPermission BIT = NULL,
    @HasDeletingCategoryPermission BIT = NULL,
    @HasCreatingCompanyPermission BIT = NULL,
    @HasReadingCompanyPermission BIT = NULL,
    @HasUpdatingCompanyPermission BIT = NULL,
    @HasDeletingCompanyPermission BIT = NULL,
    @HasCreatingDepartmentPermission BIT = NULL,
    @HasReadingDepartmentPermission BIT = NULL,
    @HasUpdatingDepartmentPermission BIT = NULL,
    @HasDeletingDepartmentPermission BIT = NULL,
    @HasCreatingEmployeePermission BIT = NULL,
    @HasReadingEmployeePermission BIT = NULL,
    @HasUpdatingEmployeePermission BIT = NULL,
    @HasDeletingEmployeePermission BIT = NULL,
    @HasCreatingEndUserPermission BIT = NULL,
    @HasReadingEndUserPermission BIT = NULL,
    @HasUpdatingEndUserPermission BIT = NULL,
    @HasDeletingEndUserPermission BIT = NULL,
    @HasCreatingEndUserRolePermission BIT = NULL,
    @HasReadingEndUserRolePermission BIT = NULL,
    @HasUpdatingEndUserRolePermission BIT = NULL,
    @HasDeletingEndUserRolePermission BIT = NULL,
    @HasCreatingLocationPermission BIT = NULL,
    @HasReadingLocationPermission BIT = NULL,
    @HasUpdatingLocationPermission BIT = NULL,
    @HasDeletingLocationPermission BIT = NULL,
    @HasCreatingManufacturerPermission BIT = NULL,
    @HasReadingManufacturerPermission BIT = NULL,
    @HasUpdatingManufacturerPermission BIT = NULL,
    @HasDeletingManufacturerPermission BIT = NULL,
    @HasCreatingProductPermission BIT = NULL,
    @HasReadingProductPermission BIT = NULL,
    @HasUpdatingProductPermission BIT = NULL,
    @HasDeletingProductPermission BIT = NULL,
    @HasCreatingProductSetPermission BIT = NULL,
    @HasReadingProductSetPermission BIT = NULL,
    @HasUpdatingProductSetPermission BIT = NULL,
    @HasDeletingProductSetPermission BIT = NULL,
    @HasCreatingRolePermission BIT = NULL,
    @HasReadingRolePermission BIT = NULL,
    @HasUpdatingRolePermission BIT = NULL,
    @HasDeletingRolePermission BIT = NULL,
    @HasReadingStoredProcedureLogPermission BIT = NULL,
    @HasDeletingStoredProcedureLogPermission BIT = NULL,
    @HasCreatingVendorPermission BIT = NULL,
    @HasReadingVendorPermission BIT = NULL,
    @HasUpdatingVendorPermission BIT = NULL,
    @HasDeletingVendorPermission BIT = NULL
AS;
BEGIN
    SET NOCOUNT ON;

    -- Check creating permission of the calling EndUser.
    DECLARE @CallingEndUserHasCreatingEndUserRolePermission BIT = (SELECT HasCreatingEndUserRolePermission FROM [dbo].[tvf_GetCRUDPermissionsOfEndUser](@CallingEndUserId));

    IF (@CallingEndUserHasCreatingEndUserRolePermission IS NULL)
        BEGIN
            RAISERROR ('@CallingEndUserId does not exist!', 11, 0);
            RETURN -1;
        END;
    IF (@CallingEndUserHasCreatingEndUserRolePermission = 0)
        BEGIN
            RAISERROR ('@CallingEndUserId has no permission to create an EndUserRole!', 11, 0);
            RETURN -1;
        END;

    -- Run actual query.
    INSERT INTO [dbo].[EndUserRole] (
        Name,
        HasCreatingAssetPermission,
        HasReadingAssetPermission,
        HasUpdatingAssetPermission,
        HasDeletingAssetPermission,
        HasCreatingBuildingPermission,
        HasReadingBuildingPermission,
        HasUpdatingBuildingPermission,
        HasDeletingBuildingPermission,
        HasCreatingCategoryPermission,
        HasReadingCategoryPermission,
        HasUpdatingCategoryPermission,
        HasDeletingCategoryPermission,
        HasCreatingCompanyPermission,
        HasReadingCompanyPermission,
        HasUpdatingCompanyPermission,
        HasDeletingCompanyPermission,
        HasCreatingDepartmentPermission,
        HasReadingDepartmentPermission,
        HasUpdatingDepartmentPermission,
        HasDeletingDepartmentPermission,
        HasCreatingEmployeePermission,
        HasReadingEmployeePermission,
        HasUpdatingEmployeePermission,
        HasDeletingEmployeePermission,
        HasCreatingEndUserPermission,
        HasReadingEndUserPermission,
        HasUpdatingEndUserPermission,
        HasDeletingEndUserPermission,
        HasCreatingEndUserRolePermission,
        HasReadingEndUserRolePermission,
        HasUpdatingEndUserRolePermission,
        HasDeletingEndUserRolePermission,
        HasCreatingLocationPermission,
        HasReadingLocationPermission,
        HasUpdatingLocationPermission,
        HasDeletingLocationPermission,
        HasCreatingManufacturerPermission,
        HasReadingManufacturerPermission,
        HasUpdatingManufacturerPermission,
        HasDeletingManufacturerPermission,
        HasCreatingProductPermission,
        HasReadingProductPermission,
        HasUpdatingProductPermission,
        HasDeletingProductPermission,
        HasCreatingProductSetPermission,
        HasReadingProductSetPermission,
        HasUpdatingProductSetPermission,
        HasDeletingProductSetPermission,
        HasCreatingRolePermission,
        HasReadingRolePermission,
        HasUpdatingRolePermission,
        HasDeletingRolePermission,
        HasReadingStoredProcedureLogPermission,
        HasDeletingStoredProcedureLogPermission,
        HasCreatingVendorPermission,
        HasReadingVendorPermission,
        HasUpdatingVendorPermission,
        HasDeletingVendorPermission
    )
    OUTPUT
        INSERTED.Id,
        INSERTED.Name,
        INSERTED.EndUserRoleCreationDate,
        INSERTED.HasCreatingAssetPermission,
        INSERTED.HasReadingAssetPermission,
        INSERTED.HasUpdatingAssetPermission,
        INSERTED.HasDeletingAssetPermission,
        INSERTED.HasCreatingBuildingPermission,
        INSERTED.HasReadingBuildingPermission,
        INSERTED.HasUpdatingBuildingPermission,
        INSERTED.HasDeletingBuildingPermission,
        INSERTED.HasCreatingCategoryPermission,
        INSERTED.HasReadingCategoryPermission,
        INSERTED.HasUpdatingCategoryPermission,
        INSERTED.HasDeletingCategoryPermission,
        INSERTED.HasCreatingCompanyPermission,
        INSERTED.HasReadingCompanyPermission,
        INSERTED.HasUpdatingCompanyPermission,
        INSERTED.HasDeletingCompanyPermission,
        INSERTED.HasCreatingDepartmentPermission,
        INSERTED.HasReadingDepartmentPermission,
        INSERTED.HasUpdatingDepartmentPermission,
        INSERTED.HasDeletingDepartmentPermission,
        INSERTED.HasCreatingEmployeePermission,
        INSERTED.HasReadingEmployeePermission,
        INSERTED.HasUpdatingEmployeePermission,
        INSERTED.HasDeletingEmployeePermission,
        INSERTED.HasCreatingEndUserPermission,
        INSERTED.HasReadingEndUserPermission,
        INSERTED.HasUpdatingEndUserPermission,
        INSERTED.HasDeletingEndUserPermission,
        INSERTED.HasCreatingEndUserRolePermission,
        INSERTED.HasReadingEndUserRolePermission,
        INSERTED.HasUpdatingEndUserRolePermission,
        INSERTED.HasDeletingEndUserRolePermission,
        INSERTED.HasCreatingLocationPermission,
        INSERTED.HasReadingLocationPermission,
        INSERTED.HasUpdatingLocationPermission,
        INSERTED.HasDeletingLocationPermission,
        INSERTED.HasCreatingManufacturerPermission,
        INSERTED.HasReadingManufacturerPermission,
        INSERTED.HasUpdatingManufacturerPermission,
        INSERTED.HasDeletingManufacturerPermission,
        INSERTED.HasCreatingProductPermission,
        INSERTED.HasReadingProductPermission,
        INSERTED.HasUpdatingProductPermission,
        INSERTED.HasDeletingProductPermission,
        INSERTED.HasCreatingProductSetPermission,
        INSERTED.HasReadingProductSetPermission,
        INSERTED.HasUpdatingProductSetPermission,
        INSERTED.HasDeletingProductSetPermission,
        INSERTED.HasCreatingRolePermission,
        INSERTED.HasReadingRolePermission,
        INSERTED.HasUpdatingRolePermission,
        INSERTED.HasDeletingRolePermission,
        INSERTED.HasReadingStoredProcedureLogPermission,
        INSERTED.HasDeletingStoredProcedureLogPermission,
        INSERTED.HasCreatingVendorPermission,
        INSERTED.HasReadingVendorPermission,
        INSERTED.HasUpdatingVendorPermission,
        INSERTED.HasDeletingVendorPermission
    VALUES (
        @Name,
        COALESCE(@HasCreatingAssetPermission, 0),
        COALESCE(@HasReadingAssetPermission, 0),
        COALESCE(@HasUpdatingAssetPermission, 0),
        COALESCE(@HasDeletingAssetPermission, 0),
        COALESCE(@HasCreatingBuildingPermission, 0),
        COALESCE(@HasReadingBuildingPermission, 0),
        COALESCE(@HasUpdatingBuildingPermission, 0),
        COALESCE(@HasDeletingBuildingPermission, 0),
        COALESCE(@HasCreatingCategoryPermission, 0),
        COALESCE(@HasReadingCategoryPermission, 0),
        COALESCE(@HasUpdatingCategoryPermission, 0),
        COALESCE(@HasDeletingCategoryPermission, 0),
        COALESCE(@HasCreatingCompanyPermission, 0),
        COALESCE(@HasReadingCompanyPermission, 0),
        COALESCE(@HasUpdatingCompanyPermission, 0),
        COALESCE(@HasDeletingCompanyPermission, 0),
        COALESCE(@HasCreatingDepartmentPermission, 0),
        COALESCE(@HasReadingDepartmentPermission, 0),
        COALESCE(@HasUpdatingDepartmentPermission, 0),
        COALESCE(@HasDeletingDepartmentPermission, 0),
        COALESCE(@HasCreatingEmployeePermission, 0),
        COALESCE(@HasReadingEmployeePermission, 0),
        COALESCE(@HasUpdatingEmployeePermission, 0),
        COALESCE(@HasDeletingEmployeePermission, 0),
        COALESCE(@HasCreatingEndUserPermission, 0),
        COALESCE(@HasReadingEndUserPermission, 0),
        COALESCE(@HasUpdatingEndUserPermission, 0),
        COALESCE(@HasDeletingEndUserPermission, 0),
        COALESCE(@HasCreatingEndUserRolePermission, 0),
        COALESCE(@HasReadingEndUserRolePermission, 0),
        COALESCE(@HasUpdatingEndUserRolePermission, 0),
        COALESCE(@HasDeletingEndUserRolePermission, 0),
        COALESCE(@HasCreatingLocationPermission, 0),
        COALESCE(@HasReadingLocationPermission, 0),
        COALESCE(@HasUpdatingLocationPermission, 0),
        COALESCE(@HasDeletingLocationPermission, 0),
        COALESCE(@HasCreatingManufacturerPermission, 0),
        COALESCE(@HasReadingManufacturerPermission, 0),
        COALESCE(@HasUpdatingManufacturerPermission, 0),
        COALESCE(@HasDeletingManufacturerPermission, 0),
        COALESCE(@HasCreatingProductPermission, 0),
        COALESCE(@HasReadingProductPermission, 0),
        COALESCE(@HasUpdatingProductPermission, 0),
        COALESCE(@HasDeletingProductPermission, 0),
        COALESCE(@HasCreatingProductSetPermission, 0),
        COALESCE(@HasReadingProductSetPermission, 0),
        COALESCE(@HasUpdatingProductSetPermission, 0),
        COALESCE(@HasDeletingProductSetPermission, 0),
        COALESCE(@HasCreatingRolePermission, 0),
        COALESCE(@HasReadingRolePermission, 0),
        COALESCE(@HasUpdatingRolePermission, 0),
        COALESCE(@HasDeletingRolePermission, 0),
        COALESCE(@HasReadingStoredProcedureLogPermission, 0),
        COALESCE(@HasDeletingStoredProcedureLogPermission, 0),
        COALESCE(@HasCreatingVendorPermission, 0),
        COALESCE(@HasReadingVendorPermission, 0),
        COALESCE(@HasUpdatingVendorPermission, 0),
        COALESCE(@HasDeletingVendorPermission, 0)
    );
END;
