CREATE TABLE [dbo].[AssetFix] (
    [AssetFixNumber] INT IDENTITY (1, 1),
    [AssetFixID] UNIQUEIDENTIFIER CONSTRAINT [DF_AssetFix_AssetFixID] DEFAULT (NEWID()) NOT NULL,
    [AssetIssueID] UNIQUEIDENTIFIER NOT NULL,
    [AssetFixDateStart] DATETIMEOFFSET(3) CONSTRAINT [DF_AssetFix_AssetFixDateStart] DEFAULT (SYSDATETIMEOFFSET()) NOT NULL,
    [AssetFixCost] DECIMAL(15, 4) NULL,
    [AssetFixDateEnd] DATETIMEOFFSET(3) NULL,
    [AssetFixDateDays] AS DATEDIFF_BIG(DD, AssetFixDateStart, AssetFixDateEnd) PERSISTED,
    [AssetFixTitle] NVARCHAR(4000) NOT NULL,
    [AssetFixDescription] NVARCHAR(MAX) NULL,
    [AssetFixDocumentationURL] NVARCHAR(4000) NULL,
    [AssetFixed] BIT NOT NULL,
    [EmployeeID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [AK_AssetFix_AssetFixNumber] UNIQUE CLUSTERED ([AssetFixNumber] ASC),
    CONSTRAINT [PK_AssetFix] PRIMARY KEY NONCLUSTERED ([AssetFixID] ASC),
    CONSTRAINT [CK_AssetFix_AssetFixCost] CHECK ([AssetFixCost] >= (0)),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_Exclude] CHECK ([AssetFixTitle] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_MinimumLength] CHECK (LEN([AssetFixTitle]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixTitle] NOT LIKE ' %' AND [AssetFixTitle] NOT LIKE '% '),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_Exclude] CHECK ([AssetFixDescription] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_MinimumLength] CHECK (LEN([AssetFixDescription]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixDescription] NOT LIKE ' %' AND [AssetFixDescription] NOT LIKE '% '),
    CONSTRAINT [CK_AssetFix_AssetFixDateEnd_Exclude] CHECK ([AssetFixDateEnd] NOT IN (CONVERT(DATETIMEOFFSET(3), '1900-01-01T00:00:00.000Z'), CONVERT(DATETIMEOFFSET(3), '2900-01-01T00:00:00.000Z'))),
    CONSTRAINT [CK_AssetFix_AssetFixCost_Exclude] CHECK ([AssetFixCost] NOT IN (CONVERT(DECIMAL(15, 4), -99999999999.9999), CONVERT(DECIMAL(15, 4), 99999999999.9999))),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_Exclude] CHECK ([AssetFixDocumentationURL] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_MinimumLength] CHECK (LEN([AssetFixDocumentationURL]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixDocumentationURL] NOT LIKE ' %' AND [AssetFixDocumentationURL] NOT LIKE '% '),
    CONSTRAINT [CK_AssetFix_AssetFixDateDays_Exclude] CHECK ([AssetFixDateDays] NOT IN (CONVERT(BIGINT, -9223372036854775808), CONVERT(BIGINT, 9223372036854775807))),
    CONSTRAINT [CTK_AssetFix_AssetFixDateEnd_AssetFixDateStart] CHECK ([AssetFixDateEnd] >= [AssetFixDateStart]),
    CONSTRAINT [FK_AssetFix_AssetIssue] FOREIGN KEY ([AssetIssueID]) REFERENCES [dbo].[AssetIssue] ([AssetIssueID]),
    CONSTRAINT [FK_AssetFix_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employee] ([EmployeeID])
);
