CREATE TABLE [dbo].[AssetFix] (
    [AssetFixNumber] INT IDENTITY (1, 1),
    [AssetFixID] UNIQUEIDENTIFIER CONSTRAINT [DF_AssetFix_AssetFixID] DEFAULT (NEWID()) NOT NULL,
    [AssetIssueID] UNIQUEIDENTIFIER NOT NULL,
    [AssetFixDateStart] DATETIME CONSTRAINT [DF_AssetFix_AssetFixDateStart] DEFAULT (GETDATE()) NOT NULL,
    [AssetFixCost] DECIMAL(19, 4) NULL,
    [AssetFixDateEnd] DATETIME NULL,
    [AssetFixTitle] NVARCHAR(4000) NOT NULL,
    [AssetFixDescription] NVARCHAR(MAX) NULL,
    [AssetFixDocumentationURL] NVARCHAR(4000) NULL,
    [AssetFixed] BIT NOT NULL,
    [EmployeeID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [AK_AssetFix_AssetFixNumber] UNIQUE CLUSTERED ([AssetFixNumber] ASC),
    CONSTRAINT [PK_AssetFix] PRIMARY KEY NONCLUSTERED ([AssetFixID] ASC),
    CONSTRAINT [CK_AssetFix_AssetFixCost] CHECK ([AssetFixCost] >= (0)),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_Exclude] CHECK ([AssetFixTitle] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_MinimumLength] CHECK (LEN([AssetFixTitle]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixTitle_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixTitle] NOT LIKE ' %' AND [AssetFixTitle] NOT LIKE '% '),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_Exclude] CHECK ([AssetFixDescription] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_MinimumLength] CHECK (LEN([AssetFixDescription]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixDescription_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixDescription] NOT LIKE ' %' AND [AssetFixDescription] NOT LIKE '% '),
    CONSTRAINT [CK_AssetFix_AssetFixDateEnd_Exclude] CHECK ([AssetFixDateEnd] NOT IN (CONVERT(DATETIME, '1753-01-01 00:00:00.000'), CONVERT(DATETIME, '9999-12-31 23:59:59.997'))),
    CONSTRAINT [CK_AssetFix_AssetFixCost_Exclude] CHECK ([AssetFixCost] NOT IN (CONVERT(DECIMAL(19, 4), -999999999999999.9999), CONVERT(DECIMAL(19, 4), 999999999999999.9999))),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_Exclude] CHECK ([AssetFixDocumentationURL] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_MinimumLength] CHECK (LEN([AssetFixDocumentationURL]) > 0),
    CONSTRAINT [CK_AssetFix_AssetFixDocumentationURL_NoLeadingAndTrailingWhitespace] CHECK ([AssetFixDocumentationURL] NOT LIKE ' %' AND [AssetFixDocumentationURL] NOT LIKE '% '),
    CONSTRAINT [CTK_AssetFix_AssetFixDateEnd_AssetFixDateStart] CHECK ([AssetFixDateEnd] >= [AssetFixDateStart]),
    CONSTRAINT [FK_AssetFix_AssetIssue] FOREIGN KEY ([AssetIssueID]) REFERENCES [dbo].[AssetIssue] ([AssetIssueID]),
    CONSTRAINT [FK_AssetFix_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employee] ([EmployeeID])
);
