CREATE TABLE [dbo].[Company] (
    [CompanyNumber] INT IDENTITY (1, 1),
    [CompanyID] UNIQUEIDENTIFIER CONSTRAINT [DF_Company_CompanyID] DEFAULT (NEWID()) NOT NULL,
    [ParentCompanyID] UNIQUEIDENTIFIER NULL,
    [CompanyName] NVARCHAR(850) NOT NULL,
    [CompanyAddress] NVARCHAR(850) NOT NULL,
    [CompanyCode] NVARCHAR(5) NOT NULL,
    [CompanyInsertDate] DATETIME CONSTRAINT [DF_Company_CompanyInsertDate] DEFAULT (GETDATE()) NOT NULL,
    CONSTRAINT [AK_Company_CompanyNumber] UNIQUE CLUSTERED ([CompanyNumber] ASC),
    CONSTRAINT [AK_Company_CompanyName] UNIQUE ([CompanyName]),
    CONSTRAINT [AK_Company_CompanyAddress] UNIQUE ([CompanyAddress]),
    CONSTRAINT [AK_Company_CompanyCode] UNIQUE ([CompanyCode]),
    CONSTRAINT [CK_Company_CompanyName_Exclude] CHECK ([CompanyName] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_Company_CompanyName_MinimumLength] CHECK (LEN([CompanyName]) > 0),
    CONSTRAINT [CK_Company_CompanyName_NoLeadingAndTrailingWhitespace] CHECK ([CompanyName] NOT LIKE ' %' AND [CompanyName] NOT LIKE '% '),
    CONSTRAINT [CK_Company_CompanyAddress_Exclude] CHECK ([CompanyAddress] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_Company_CompanyAddress_MinimumLength] CHECK (LEN([CompanyAddress]) > 0),
    CONSTRAINT [CK_Company_CompanyAddress_NoLeadingAndTrailingWhitespace] CHECK ([CompanyAddress] NOT LIKE ' %' AND [CompanyAddress] NOT LIKE '% '),
    CONSTRAINT [CK_Company_CompanyCode_Exclude] CHECK ([CompanyCode] NOT IN ('', '!', 'NULL')),
    CONSTRAINT [CK_Company_CompanyCode_MinimumLength] CHECK (LEN([CompanyCode]) > 0),
    CONSTRAINT [CK_Company_CompanyCode_NoLeadingAndTrailingWhitespace] CHECK ([CompanyCode] NOT LIKE ' %' AND [CompanyCode] NOT LIKE '% '),
    CONSTRAINT [PK_Company] PRIMARY KEY NONCLUSTERED ([CompanyID] ASC),
    CONSTRAINT [FK_Company_Company] FOREIGN KEY ([ParentCompanyID]) REFERENCES [dbo].[Company] ([CompanyID]),
    CONSTRAINT [CTK_Company_CompanyID_ParentCompanyID] CHECK ([CompanyID] != [ParentCompanyID])
);
