CREATE TABLE [dbo].[Role] (
    [RoleID]   UNIQUEIDENTIFIER CONSTRAINT [DF_Role_RoleID] DEFAULT (newid()) NOT NULL,
    [RoleName] NVARCHAR (50)    NOT NULL,
    CONSTRAINT [AK_Role_RoleName] UNIQUE ([RoleName]),
    CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([RoleID] ASC)
);
