CREATE FUNCTION [dbo].[udf_GetUniqueidentifier](
    @Value NVARCHAR(36)
)
RETURNS UNIQUEIDENTIFIER WITH SCHEMABINDING AS
BEGIN
    RETURN CASE
        WHEN (@Value = '')
            THEN NULL
        ELSE CAST(@Value AS UNIQUEIDENTIFIER)
    END;
END;
